# Generated by Django 6.0.1 on 2026-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
