# Generated by Django 6.0.1 on 2026-02-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_budget_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='comment',
            field=models.CharField(blank=True, default='nic', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.CharField(blank=True, verbose_name=50),
        ),
    ]
