# Generated by Django 6.0.1 on 2026-02-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_budget_comment_alter_expense_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
