# Generated by Django 6.0.1 on 2026-03-05 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_subscription_pay_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='real_cost',
        ),
        migrations.AddField(
            model_name='budget',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rzeczywisty koszt'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensescategories', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='expected_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Spodziewany koszt'),
        ),
    ]
