# Generated by Django 6.0.1 on 2026-03-14 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_budget_real_cost_budget_actual_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 14, 12, 3, 48, 947386)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
