# Generated by Django 6.0.1 on 2026-03-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_wish_created_at_wish_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensescategories'),
        ),
        migrations.AlterField(
            model_name='budgetresultexpenses',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensescategories'),
        ),
        migrations.AlterField(
            model_name='commonitem',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensescategories'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensescategories'),
        ),
        migrations.AlterField(
            model_name='need',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensescategories'),
        ),
    ]
