# Generated by Django 6.0.1 on 2026-03-16 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_wish_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
