# Generated by Django 6.0.1 on 2026-03-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_subscription_created_at_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
    ]
