# Generated by Django 6.0.1 on 2026-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_investment_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
