# Generated by Django 6.0.1 on 2026-03-15 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_investment_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='investment',
            name='current_price_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
