# Generated by Django 6.0.1 on 2026-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
