# Generated by Django 6.0.1 on 2026-02-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_alter_book_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
