# Generated by Django 6.0.1 on 2026-02-23 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_booksuggestion_moviesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
