# Generated by Django 6.0.1 on 2026-02-23 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0005_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
